### PR TITLE
[NEEDS TESTING] dcron: stop spamming the log when sendmail is not available,

### PR DESCRIPTION
**Pull request by mobinmob**
- add debug (-d) output by default to the logger
- stop dcrond from trying to use sendmail and failing
- document the options in a comment.

This is an attempt to fix https://github.com/mobinmob/void-66-services/issues/65 reported by @flexibeast. It works reliably on my machine, but seems to fail elsewere :( - it needs more testing...

### CODE REVIEW

**Comment by flexibeast** [comment]
This works for me! Though i thought i'd initially tried what you have here .... just using `/bin/true` instead of `/usr/bin/true`, though they're represented by the same inode on my system. At any rate, thanks!

**Comment by mobinmob** [comment]
Nice ;) Thanks for discovering the issue and testing! 
I have not found a generic way to capture the ouput of the jobs running. I highly suggest using [snooze](https://github.com/leahneukirchen/snooze) instead of a cron implementation for this.

**Comment by flexibeast** [comment]
Most welcome!
i don't usually need to be handling job output via the daemon itself, so doing so typically isn't a concern for me. (Although i believe one can redirect output for individual jobs via `>` in the appropriate crontab line?) Still, if that changes, i'll definitely keep `snooze` in mind. :-)

**Comment by mobinmob** [comment]
Yes, redirection in every cron job is possible 😉

**Pull request merged**
