### PR TITLE
[WIP] repo-wide: remove @options when it is not needed, standardize:

### PR DESCRIPTION
**Pull request by mobinmob**
Due to some 66 changes, the @options key is not needed in most cases.
Τhe logger is now opt-out and the [environment] is automatically
recognized.
With this commit I am removing unneeded @options keys. I am also making
sure that between sections there is always a single newline and also a
single newline at the end. This is not some misguided attempt to
save some space. I want to be consistent, as new services do not have an
option key if it is not necessary. I am happy that this frontend service
file collections is getting some use outside of voidlinux and I want to
have consistent style to help anyone that finds them useful.

@ndowens

### CODE REVIEW

**Comment by ndowens** [comment]
Thank you. I am enjoying 66 myself and working on getting 66 on Artix as well, while trying to provide credit for where I got the scripts(here). Currently I am adding both the License and 3rd-party one and Author to currently just my personal 66-services repo until it is more official, which even then will be put in the official repo as well. I want to give credit where I can. Currently it is root dir of my script repo.

**Comment by mobinmob** [comment]
> Thank you. I am enjoying 66 myself and working on getting 66 on Artix as well, while trying to provide credit for where I got the scripts(here). Currently I am adding both the License and 3rd-party one and Author to currently just my personal 66-services repo until it is more official, which even then will be put in the official repo as well. I want to give credit where I can. Currently it is root dir of my script repo.

You will need some modifications - not much I hope. I tried to follow the voidlinux runit services scripts and there are really simple. obarun has a differenty style - more complete control, but more complicated also. There are also built for archlinux based/derived distributions. 
I tried to make the licensing situation as clear as possible (different  files etc) but I can tell it seems confusing :( . If you have a suggestion to improve this, I will gladly hear it. Having the licensing information for me is not just (or even mainly...) about giving credit. It is to create a relation between the repos and enable sharing of improvements or corrections.  If you add work to this collection, you should add your copyright there...

**Comment by ndowens** [comment]
> > Thank you. I am enjoying 66 myself and working on getting 66 on Artix as well, while trying to provide credit for where I got the scripts(here). Currently I am adding both the License and 3rd-party one and Author to currently just my personal 66-services repo until it is more official, which even then will be put in the official repo as well. I want to give credit where I can. Currently it is root dir of my script repo.
> 
> You will need some modifications - not much I hope. I tried to follow the voidlinux runit services scripts and there are really simple. obarun has a differenty style - more complete control, but more complicated also. There are also built for archlinux based/derived distributions.
> I tried to make the licensing situation as clear as possible (different files etc) but I can tell it seems confusing :( . If you have a suggestion to improve this, I will gladly hear it. Having the licensing information for me is not just (or even mainly...) about giving credit. It is to create a relation between the repos and enable sharing of improvements or corrections. If you add work to this collection, you should add your copyright there...

So far I've only had to change one of yours, elogind as ours uses openrc cgroup backend and also path for elogind is different.

**Comment by mobinmob** [comment]
> > > Thank you. I am enjoying 66 myself and working on getting 66 on Artix as well, while trying to provide credit for where I got the scripts(here). Currently I am adding both the License and 3rd-party one and Author to currently just my personal 66-services repo until it is more official, which even then will be put in the official repo as well. I want to give credit where I can. Currently it is root dir of my script repo.
> > 
> > 
> > You will need some modifications - not much I hope. I tried to follow the voidlinux runit services scripts and there are really simple. obarun has a differenty style - more complete control, but more complicated also. There are also built for archlinux based/derived distributions.
> > I tried to make the licensing situation as clear as possible (different files etc) but I can tell it seems confusing :( . If you have a suggestion to improve this, I will gladly hear it. Having the licensing information for me is not just (or even mainly...) about giving credit. It is to create a relation between the repos and enable sharing of improvements or corrections. If you add work to this collection, you should add your copyright there...
> 
> So far I've only had to change one of yours, elogind as ours uses openrc cgroup backend and also path for elogind is different.

elogind is a work of @teldra. He went above and beyond... The voidlinux service just launches a wrapper. This is the complete script in execline!

**Comment by ndowens** [comment]
When ever I get to the point of adding services to streamline 66's services with all the services we have, I can open PRs for new services you may not have at that time. Look forward to collaborating with you in the future :)

**Comment by mobinmob** [comment]
> But this is only an Artix case, but I wouldn't mind adding/PR'ing services, as we have some in our repo I will have to add to 66 that isn't here :)

I will gladly accept PRs :) 
voidlinux has about 500 runit scripts and I am slowly transforming them. I am not in a hurry as I can run almost all "missing" ones run with... the runit service - check the runit frontend on my [PR](https://github.com/void-linux/void-packages/pull/25743).

>Look forward to collaborating with you in the future :)

Please do not hesitate to ask anything on the construction of frontends or boot-66serv - even on email.

**Comment by mobinmob** [comment]
Ok, I think every services is adjusted. I will check them again and merge :)

**Comment by mobinmob** [comment]
Merges in 16d7bbdbafd5419d011e31d10aeb04cc95be2fec.

**Pull request closed without merging**
