### PR TITLE
New services: piperwire_user

### PR DESCRIPTION
**Pull request by gspe**
This is a simple user service for pipewire.
I'd like to make pipewire_user `@extdepends = ( dbus ) ` but not seams to be possible.

### CODE REVIEW

**Comment by mobinmob** [comment]
Thank you for writing a user service!
What is the problem with having dbus in @extdepends? 
Please do not include the PATH in the @execute key. The supervisor starts with a clean and predictable environment already.

**Comment by mobinmob** [comment]
@gspe Seems that merging and deleting the devel branch closed the PR. I will try to reopen but I see no way in the github ui...

**Comment by gspe** [comment]
> Thank you for writing a user service!
> What is the problem with having dbus in `@extdepends`?

@mobinmob if I use `@extdepends = ( dbus )` I get this error:
```
66-enable -v 4 -t base -C -F pipewire_user
66-enable(src/lib66/parser_enabled.c: parse_service_before: 40): tracing: start parse process of service: /etc/66/service/pipewire_user
66-enable(src/lib66/parser_enabled.c: parse_service_before: 80): tracing: read service file of: /etc/66/service/pipewire_user
66-enable(src/lib66/parser_enabled.c: parse_service_deps: 235): tracing: /etc/66/service/pipewire_user: haven't dependencies
66-enable(src/lib66/parser_enabled.c: parse_service_before: 40): tracing: start parse process of service: /usr/share/66/service/dbus
66-enable(src/lib66/parser_enabled.c: parse_service_before: 80): tracing: read service file of: /usr/share/66/service/dbus
66-enable(src/lib66/parser_utils.c: keep_common: 601): warning: unable to use the service -- permission denied
66-enable(src/lib66/parser.c: parser: 70): warning: unable to keep information of service file: dbus
66-enable(src/lib66/ssexec_enable.c: start_parser: 76): fatal: unable to parse service file: /etc/66/service/pipewire_user: or its dependencies
```
seams that as user I can't declare a dependency that run as root or something similar

**Comment by mobinmob** [comment]
@gspe : Ι have published the first release. I still have to review the basic documentation and maybe publich a couple of scripts. For 0.0.2 or -most likely- 0.0.3 focus will be in user-services :)

**Pull request closed without merging**
