### PR TITLE
[WIP] New service: gdm.

### PR DESCRIPTION
**Pull request by mobinmob**
The service needs more testing.
In a pc with an nvidia driver, one must have `needs_root_rights = yes` in `/etc/X11/Xwrapper.config` in order to start the daemon. Many thanks to @linuxergr who suggested the above.

### CODE REVIEW

**Comment by paper42** [comment]
As we discussed on IRC, elogind needs to be in extdepends for Wayland sessions to work.

There is a race condition between gdm and something else (maybe elogind?) - gdm can start when it isn't ready which means that gdm falls back to the xorg backend which results in it not being able to launch wayland sessions. `66-stop gdm && 66-start gdm` makes it launch with the wayland backend.

I tried using an [elogind readiness check](https://github.com/st3r4g/void-s6/blob/main/void/elogind/data/check), but it didn't help. I might be just doing something wrong.

**Comment by mobinmob** [comment]
@paper42  There are more problems without elogind, even with the xorg backend when starting other DEs. I am going to do more testing today on two different systems (nvidia with nouveau/ intel gpus), thank you for the testing :)

**Comment by paper42** [comment]
@mobinmob I think you were able to reproduce the issue, right? Could you push the version that delays the gdm start at least for now, so that the service in this PR is fully functional?

**Comment by mobinmob** [comment]
@paper42 I pushed a **somewhat** fixed service. I added an if block that just contains a s6-sleep invocation for a second and a s6-echo invocation to pring a message to the log.
That works for an xorg session with `needs_root_rights` = yes in `/etc/X11/Xwrapper.config` .

**Pull request merged**
