### PR TITLE
Suggestions_for_services: include clarification of the [stop] stanza

### PR DESCRIPTION
**Pull request by mobinmob**
@flexibeast : I hope that is ok, suggestions welcome :)

### CODE REVIEW

**Comment by flexibeast** [comment]
This looks good, thanks! i know you've merged it, but a couple of things i'd like to mention are:

* a typo, "whould" instead of "would"; and re.:

    `@version value should always be @VERSION@`

Is there some way to be able to use this during development? (i had `@VERSION@` initially, then provided a specific value when 66 complained.) If not, i would mention that a specific version number needs to be provided during development, but that the final service file should have `@VERSION@`.

**Comment by mobinmob** [comment]
> This looks good, thanks! i know you've merged it, but a couple of things i'd like to mention are:
> 
>     * a typo, "whould" instead of "would"; and re.:
>       `@version value should always be @VERSION@`
> 
Thanks! I will create a new PR ;)

> 
> Is there some way to be able to use this during development? (i had `@VERSION@` initially, then provided a specific value when 66 complained.) If not, i would mention that a specific version number needs to be provided during development, but that the final service file should have `@VERSION@`.

That is whole reason for the makefile :) 
`@VERSION@` as an idea comes from obarun. @teldra  wanted to use vsed in a template in order to install a new version of the files, but that doesn't really help during development/testing. I create/modify templates in my local repo clone, install them with make and use them directly. That has the added benefit that everything uses the next release version number.

**Comment by flexibeast** [comment]
> I create/modify templates in my local repo clone, install them with make and use them directly.

Ah, that makes sense; i'd just been copying the service from the local repo to `/etc/66/service/`. i'll start using your approach instead. :-)

**Comment by mobinmob** [comment]
I did something like that in the beginning... it gets problematic really fast if you are working with/fixing multiple frontends. Make is also for both the user that wants to test the services.

**Pull request merged**
