### PR TITLE
[WIP] nginx: Add service.

### PR DESCRIPTION
**Pull request by flexibeast**
Based on the Void runit service.

Unfortunately, i can't get it to work. :-( `66-inservice` reports:

> enabled, down (exitcode 0) 0 seconds, normally up, want up, ready 0 seconds

### CODE REVIEW

**Comment by mobinmob** [comment]
Thank you for the frontend! 
I have a working nginx in my [more-services PR](https://github.com/mobinmob/void-66-services/pull/14/commits/069034c5c0824cce6d94d440d285c4d3cfccab56). That seems more complete, I 'd rather merge it instead of mine :P
The problem is that you need double-quoting in 'daemon off;' ;)  You also do not need execl-cmdline for just command switches - you need it when there is a variable.
Do you need the stop stanza?

**Comment by flexibeast** [comment]
> The problem is that you need double-quoting in 'daemon off;' ;)

Hmm .... Regardless of whether i try (no `execl-cmdline`):

* `nginx -g "'daemon off;'"`
* `nginx "-g 'daemon off;'"`
* `nginx -g "daemon off;"`
* `nginx -g 'daemon off;'`

and even:

`execl-cmdline -s { nginx ${cmd_args} }`

with an `[environment]` stanza:

    [environment]
    cmd_args=!-g "daemon off;"

the result is the same:

    nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
    nginx: invalid option: "off;'"

> Do you need the stop stanza?

i wasn't sure, but [this Obarun service](https://framagit.org/pkg/observice/nginx-66serv/-/blob/master/version/0.2.0-1/nginx) has it ...

**Comment by mobinmob** [comment]
> > The problem is that you need double-quoting in 'daemon off;' ;)
> 
> Hmm .... Regardless of whether i try (no `execl-cmdline`):
> 
>     * `nginx -g "'daemon off;'"`
> 
>     * `nginx "-g 'daemon off;'"`
> 
>     * `nginx -g "daemon off;"`
> 
>     * `nginx -g 'daemon off;'`
> 
> 
> and even:
> 
> `execl-cmdline -s { nginx ${cmd_args} }`
> 
> with an `[environment]` stanza:
> 
> ```
> [environment]
> cmd_args=!-g "daemon off;"
> ```
> 
> the result is the same:
> 
> ```
> nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
> nginx: invalid option: "off;'"
> ```
> 
How do you reload the service? Just stopping and starting it again will not work.
You need to specify some of -`C `-`F ` `-f ` `-c ` in 66-enable in order to work with the updated frontend, see the [manpage](https://man.voidlinux.org/66-enable).
Reporting nginx: invalid option: "off;'" means that it is splitting `daemon off;` which should not happen when using double quotes.
See the 66-inservice output to discover what it really executed. That drove me nuts when I started - @Obarun clarified the behavior for me...


> > Do you need the stop stanza?
> 
> i wasn't sure, but [this Obarun service](https://framagit.org/pkg/observice/nginx-66serv/-/blob/master/version/0.2.0-1/nginx) has it ...

Generally speaking, if the void service does not have a finish script we tend not to use [stop]. There are exceptions, if we discover that using something in stop is safer or needed during testing. Obarun is very explicit in their frontend files, they define everything. We shy away from that, not because it is wrong but because we try to be close to what void runit services do. I have written up some of the differences in the Suggestions_for_services document. If you think we can clarify more, that is always an option.

**Comment by flexibeast** [comment]
> How do you reload the service? Just stopping and starting it again will not work.
> You need to specify some of -C -F -f -c in 66-enable in order to work with the updated frontend

i was using `66-enable -F nginx`, with the `nginx` service in the current tree. Should that have been sufficient?

> Generally speaking, if the void service does not have a finish script we tend not to use [stop]. There are exceptions, if we discover that using something in stop is safer or needed during testing.

Ah okay.

> I have written up some of the differences in the Suggestions_for_services document. If you think we can clarify more, that is always an option.

Yeah, i read over that .... Adding an item about not using `[stop]` does seem like a good idea.

**Comment by mobinmob** [comment]
> > How do you reload the service? Just stopping and starting it again will not work.
> > You need to specify some of -C -F -f -c in 66-enable in order to work with the updated frontend
> 
> i was using `66-enable -F nginx`, with the `nginx` service in the current tree. Should that have been sufficient?
> 

-F should enough for a service without [environment] but you should also give -S :( 
i tend to use` 66-enable -v4 -t tree -F -S service`. That gives me full debugging output.
Can you please send the full output of `66-inservice nginx `here?
> > Generally speaking, if the void service does not have a finish script we tend not to use [stop]. There are exceptions, if we discover that using something in stop is safer or needed during testing.
> 
> Ah okay.
> 
> > I have written up some of the differences in the Suggestions_for_services document. If you think we can clarify more, that is always an option.
> 
> Yeah, i read over that .... Adding an item about not using `[stop]` does seem like a good idea.

OK, I will prepare a patch - probably in the obarun services item...

**Comment by mobinmob** [comment]
`nginx` uses multiple workers-processes. Maybe having a [stop] section here makes sense. We do the same with dhcpcd and dhcpcd@ using `-x`.

**Comment by flexibeast** [comment]
Output of `66-inservice nginx`:

    In tree               : general
    Status                : enabled, up (pid 32274) 2 seconds                                                                                                                
    Type                  : longrun            
    Description           : nginx HTTP daemon
    Source                : /etc/66/service/nginx
    Live                  : /run/66/tree/0/general/servicedirs/nginx
    Dependencies          : nginx-log
    External dependencies : None
    Optional dependencies : None
    Start script          :          execl-toc -d /run/nginx -m 0710 -g nginx -u root
                                     nginx -g "daemon off;"
    Stop script           : None
    Environment source    : None
    Environment file      : None
    Log name              : nginx-log
    Log destination       : /var/log/66/nginx
    Log file              : 
    2020-07-14 22:29:08.242633443  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:09.243759556  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:10.244614276  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:11.245642183  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:12.246447054  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:13.247099121  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:14.247935183  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:15.249651285  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:16.250673300  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:17.250922102  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:18.252507953  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:19.253133247  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:20.256120848  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:21.257008968  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:22.256083647  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:23.257715145  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:24.257914922  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:25.259003331  nginx: [emerg] unexpected end of parameter, expecting ";" in command line
    2020-07-14 22:29:25.932062344  nginx: [emerg] unexpected end of parameter, expecting ";" in command line

Would you like the output from the `66-enable -v4 -t general -F -S nginx` i did beforehand also?

**Comment by flexibeast** [comment]
> nginx uses multiple workers-processes. Maybe having a [stop] section here makes sense.

\*nod\* Yeah, that was part of my reasoning for having such a section, but i'm not familiar enough with nginx to say for sure (i only started using it recently, to recreate the man.voidlinux.org setup locally).

**Comment by mobinmob** [comment]
It seems to be a problem that has to do with the execline syntax, as `nginx -g "daemon off;"`
alone works fine for me... What happens if you place the execl-toc invocation in a foreground  block, like it is in chronyd?
66-enable output is not needed, since the service started ;)

**Comment by flexibeast** [comment]
> What happens if you place the execl-toc invocation in a foreground block, like it is in chronyd?

That works! And then doing `66-disable -t general -S nginx` successfully stops all the `nginx` processes. Thanks for your time and patience. :-)

Should i now force-push the working service file to this PR?

**Comment by mobinmob** [comment]
Great! :wink:
Yes, force-push is fine. Just set @version = @VERSION@ .

**Comment by flexibeast** [comment]
Done!

**Comment by mobinmob** [comment]
Thank you for your first (of many I hope :P ) service :)

**Comment by flexibeast** [comment]
i hope so too. :-)

**Comment by Obarun** [comment]
If i can make some remarks:
`-F/-f means read and parse again the frontend file from the scratch`
whereas
`-c/m/C means read and parse the [environment] section from the scratch.`
Let's say you enable a service:
`66-enable nginx`
The environment section of the nginx service is written. If you do:
`66-enable -F nginx`
It read again the frontend file and write again the e.g run file, but your configuration file is not overwritten. You need to specifie it:
`66-enable -F -C nginx`
It that case the previous configuration file is completely overwritten by the one coming from the frontend file.

@flexibeast when you want to change an environment variable, change it from the configuration file (e.g /etc/66/conf/nginx) and reload the service instead of changing the [environment] section of the frontend file. If you change the [environment] section you need to specify the -c/m/C option.
Hope it's clearer for you.

About the use of the execl-toc. By default, execl-toc try to execute a program. If you do no want to execute the program use the -X option like this:
`execl-toc -X -d /run/nginx -m 0710 -g nginx -u root`
Also, you use it inside a `foreground` block without checking the exit code of that block. That's mean that you will never warned if the creation of the /run/nginx directory field. So, from my point of view, it's better to use:
`if { execl-toc -X -d /run/nginx -m 0710 -g nginx -u root }`
Now you are sure that the directory is created before trying to run the nginx daemon.

**Comment by mobinmob** [comment]
@Obarun : Thank you for the explanation!
> About the use of the execl-toc. By default, execl-toc try to execute a program. If you do no want to execute the program use the -X option like this:
> `execl-toc -X -d /run/nginx -m 0710 -g nginx -u root`
> Also, you use it inside a `foreground` block without checking the exit code of that block. That's mean that you will never warned if the creation of the /run/nginx directory field. So, from my point of view, it's better to use:
> `if { execl-toc -X -d /run/nginx -m 0710 -g nginx -u root }`
> Now you are sure that the directory is created before trying to run the nginx daemon.
We use execl-toc extensively in the repo, we should do a review of out existing use...

**Comment by flexibeast** [comment]
@Obarun:

Thanks for the explanations; they definitely clarify some things for me. Would you be open to me submitting a PR which expands the text for `-F` on the `66-enable(1)` man page?

More generally, thanks so much for the work you've put into 66 - i'm really appreciating using it. :-)

@mobinmob:

> We use execl-toc extensively in the repo, we should do a review of our frontends...

Would you like me to create a bulk-change PR for this?

**Comment by mobinmob** [comment]
> 
> Would you like me to create a bulk-change PR for this?

@teldra has started the process, I will look into them later today - once I have a well tested runit service and finish some  things.
If you have the time, please coordinate with @teldra on IRC (d_xor) in order to avoid doing double work.

**Comment by Obarun** [comment]
@flexibeast yes sure, but it doesn't mean that your PR will be accepted :p

**Comment by mobinmob** [comment]
Oh, I really like PRs that fix things :P It is just that @teldra has already done a big push with relevant fixes.

**Pull request merged**
